---
# tasks file for launch-aws-instance

 - name: Launch ec2 Instance
   ec2:
       group_id: "{{ ec2_server_security_group }}"
       count: "{{ ec2_server_instcount }}"
       instance_type: "{{ ec2_server_instance_type }}"
       image: "{{ ec2_server_image }}"
       wait: yes
       wait_timeout: 400
       region: "{{ ec2_server_region }}"
       vpc_subnet_id: "{{ ec2_subnet_instance_vpc }}"
       key_name: "{{ ec2_server_key_name }}"
       assign_public_ip: no
   register: ec2

 - name: Add the newly created EC2 instance to the local host group
   local_action: lineinfile
                 dest="./hosts"
                 regexp="{{ item.public_ip }}"
                 insertafter="[webserver]" line="{{ item.public_ip }}"
   with_items: ec2.instances

 - name: Wait for SSH to come up
   local_action: wait_for
                 host="{{ item.public_ip }}"
                 port=22
                 state=started
   with_items: ec2.instances

 - name: Add tag to Instance(s)
   local_action: ec2_tag resource="{{ item.id }}" region="{{ ec2_server_region }}" state=present
   with_items: ec2.instances
   args:
     tags:
       Name: webserver
